Startup-scripts for one line command deploy.
Otus-DevOps-2017-11/azorge_infra pull request #1
Opened 2018-04-27 12:37 UTC by azorge

2018-04-28 16:03 UTC, Nklya requested changes
Добрый день.

Алексей, есть несколько проблем:
1. Заполни полностью имя в профиле на гитхабе
2. Основная ветка репозитория - это master. В которой изначально ничего нет. 
Потом последовательно ты создаешь новые ветки, например Infra-1 и делаешь Pull request с разницей к ветке мастер. 
А сейчас у тебя все PR сделаны с дифом к  Infra-1.

Собственно нужно добавить бранч master, сделать его основным и сделать PR с ДЗ про VPN, которого сейчас нет.

2018-04-28 16:04 UTC, Nklya commented
Ну и описание нужно заполнять

<img width="266" alt="image" src="https://user-images.githubusercontent.com/26086394/39398454-e708687a-4b16-11e8-9d20-d9d6bc9147cc.png">

2018-05-03 09:41 UTC, Nklya commented
И чтобы внести еще больше ясности - каждое ДЗ зависит от другого, поэтому все остальные будут проверены после фикса этого.

2018-05-03 09:43 UTC, azorge commented
Конечно, сегодня переделаю.

2018-05-03 14:21 UTC, closed without merging